public enum AllTagNames
{
    GameOver = 18,
    LevelButton = 20,
    ResetButton = 26,
    LevelComplete = 37,
    Retry = 38,
    NextLevel = 39,
    Exit = 40,
    GUITopChain = 44,
    GUIBottom = 45,
    MovesRemaining = 57,
    Text = 71,
    TitleText = 72,
    QuoteText = 73,
    AuthorText = 74,
    Settings = 80,
    SettingsButton = 81,
    AudioSwitch = 83,
    AllValidMovesParent = 90,
    StatsTurns = 93,
    StatsMoves = 94,
    ThankYouMessage = 96,
    FOVSlider = 97,
    Star1Image = 98,
    Star2Image = 99,
    Star3Image = 100,
    LevelSelect = 101,
    Pivot = 103,
    PlayerSetTilesParent = 104,
    EnemyHere,
    EnemyNotHere,
    PlayerSprite,
    Background
}
